### ISSUE TITLE
Correct way to continually update a canvas?

### ISSUE THREAD

**Issue by edelmanjm** [fyne-io/examples#1]
Title. Right now I'm just doing this:

```
go func() {
	for true {
		myWindow.Refresh()
		time.Sleep(time.Second/60)
	}
}()
```

**Comment by andydotxyz** [comment]
Without knowing your use case I don't know exactly how to answer - but it is not normally needed to refresh a window or canvas.

When using builtin components they should refresh at appropriate times (i.e. label.SetText("New Text").
If you are coding a new widget or a wanting to animate a custom canvas then something like this might be what you want:

myWindow.Canvas().Refresh(myObject)
(or the helper method fyne.RefreshObject(myObject) which has a small overhead to find the canvas)

And if you really want to refresh the whole window then:

myWindow.Canvas().Refresh(myWindow.Content())

I realise this code looks a bit ugly, but it's not a common code path (yet?) - if it is an animation you are creating then I think we could make a much nicer API :)

**Comment by edelmanjm** [comment]
I'm create a basic 3D lib from scratch for my own learning; animation is a pretty good analogue.

**Comment by andydotxyz** [comment]
Maybe we can add a simple thing like canvas.NewAnimation(child CanvasObject, int fps)?
Is there any additional information that you think would be needed to make this work for your example?

**Comment by edelmanjm** [comment]
Framerate is intended to be dynamic, depending on the actual load. I think for now I'm going to buffer rendered frames externally then display them; I'll let you know how things go.

**Comment by edelmanjm** [comment]
I've been working on this for a while, and I seem to be having some issues figuring out how to do concurrency appropriately. Right now, I'm creating the GUI in the main thread, then attempting to spin off another thread which continually refreshes the GUI with new images sent over a channel. However, this doesn't seem to be working since the actual displaying of the GUI appears to block everything else in the main thread (including the creation of the thread that updates the image), preventing the updating from ever occurring. Running the GUI from a separate thread doesn't seem to work for some reason. Am I missing something? What's the correct way to do things?

The two files at hand (apologies for the messy code):
```
package main

import (
	"./display"
	"image"
	"image/color"
)

func main() {
	imageChannel := make(chan image.Image)
	quit := make(chan int)
	go display.CreateDisplay().DisplayImage(imageChannel, quit)
	i := image.NewRGBA(image.Rect(0, 0, 500, 500))
	for x := 0; x < i.Bounds().Dx(); x++ {
		for y := 0; y < i.Bounds().Dy(); y++ {
			i.SetRGBA(x, y, color.RGBA{0, 0, 0, 255})
		}
	}
	imageChannel <- i
}
```
```
package display

import (
	"github.com/fyne-io/fyne"
	"github.com/fyne-io/fyne/canvas"
	"github.com/fyne-io/fyne/desktop"
	"image"
	"image/color"
)

type DisplayWindow struct {
	window fyne.Window
	canvas fyne.CanvasObject

}

func (d *DisplayWindow) Layout(objects []fyne.CanvasObject, size fyne.Size) {
	d.canvas.Resize(size)
}

func (d *DisplayWindow) MinSize(objects []fyne.CanvasObject) fyne.Size {
	return fyne.NewSize(320, 240)
}

func (d *DisplayWindow) Refresh() {
	d.window.Canvas().Refresh(d.canvas)
}

func (d *DisplayWindow) DisplayImage(imageStream chan image.Image, quit chan int) {
	var i image.Image
	for {
		select {
		case imageStream <- i:
			d.canvas = canvas.NewImageFromImage(i)
			d.Refresh()
		case <-quit:
			return
		}
	}
}

// TODO any way to specify this in the interface?
func CreateDisplay() *DisplayWindow {
	window := desktop.NewApp().NewWindow("Image test")
	display := &DisplayWindow{window: window}
	display.canvas = canvas.NewRaster(func(x, y, w, h int) color.RGBA {
		return color.RGBA{255, 255, 255, 255}
	})
	window.SetContent(fyne.NewContainerWithLayout(display, display.canvas))
	// Blocking from proceeding properly
	window.Show()
	return display
}
```

**Comment by andydotxyz** [comment]
Hi,

Apologies, the documentation could be a little better in this area. window.Show() will block. That is the entry point to an application (if it's the first window) and will return when all windows close (so the application can exit).

Any threads that you want to set up should be created before you call Show().
Threading should be completely transparent in Fyne - background threads will update the GUI perfectly fine under most circumstances.

The only thing in your code that might be questionable is the re-creation of the canvas on every frame:
			d.canvas = canvas.NewImageFromImage(i)
It would be better to re-use an existing image object.
Notice in the NewContainerWithLayout() you pass the display.canvas? When you overwrite d.canvas that new object is not being shown, so only the old one remains visible.

You probably need to switch out the Image.PixelColor function to point to a new buffer. I think the problem is that the NewImageFrom... APIs are basically convenience functions and some possible Image.Set.. functions need to be added.

Why not pop onto the gopher Slack #Fyne channel so we can discuss?
https://gophers.slack.com/app_redirect?channel=fyne

**Comment by andydotxyz** [comment]
I guess the shorter answer is that window.Show() is normally the last thing to call - the minimal change is to move the window show until after the CreateDisplay call and after starting a goroutine to listen for buffers to show...

**Comment by andydotxyz** [comment]
Thinking more about this it's probably good to re-use the NewRaster that you have created. If you then pass the image ready to display somehow and have it read the new data. 

Basically re-using the code from the helper function NewImageFromImage:

		PixelColor: func(x, y, w, h int) color.RGBA {
			r, g, b, a := img.At(x, y).RGBA()
			return color.RGBA{uint8(r), uint8(g), uint8(b), uint8(a)}
		},

**Comment by andydotxyz** [comment]
I thought more about the Show() confusion and have changed semantics.
window.Show() no longer blocks :) when you are ready to start the event loop you can use app.Run().

There is also a convenience function window.ShowAndRun() which does what Show() used to.

I also updated the documentation to indicate that Run() or ShowAndRun() should be called from late in your main() function.
I hope this helps.
