### ISSUE TITLE
Stack allocation leak

### ISSUE THREAD

**Issue by steveoc64** [fyne-io/examples#11]
During debugging of the game of life, found that memory allocation looks OK, but there is a definite leak in the stack usage.

See https://github.com/fyne-io/examples/pull/10 for findings.

Currently investigating - might take a weekend to sort this one out.

**Comment by steveoc64** [comment]
This is going to be fun to debug.  :)

If you run half a dozen Life's and let them go - the stack usage levels off at around 1.6MB and growth slows ... then the number of goroutines starts climbing drastically.

After a few minutes, stack tops out at just under 5MB, and the runtime.NumGoroutine() hits 2000 .. and the machine locks up hard with the CPUs pegged.  Ctrl-C to get out, because its not even registering clicks anymore.

**Comment by steveoc64** [comment]
Update - running similar test on Mac OSX Mojave on a MacBook Pro with Radeon == really good.

Issues above are with Linux (Ubuntu 18.10 up to date, with latest nVidia drivers)

Anyway, on the Mac, Im running 8 lifes in parallel, stack size grows very slowly, and remains stable at around 1.3MB.

Goroutines sit nice and stable too at around 20 (with 8 lifes running) ... but I did notice a couple of times when they burst up to to around 60-80 goroutines, but then recovers pretty quick. Callbacks from GL backing up or something ?  dont know.

Did notice on the mac that from one call to repaint life to the next, there is a fair bit of allocation / free going on still. Would like to find whats causing that.

**Comment by andydotxyz** [comment]
I think this is resolved by the upstream changes.
Can we close?

**Comment by steveoc64** [comment]
closed - actually caused by hitting the GC wall, because spawing too many new images.

Fixed by re-using a cached image in the life example rewrite
