### ISSUE TITLE
Enable anti-aliasing

### ISSUE THREAD

**Issue by dimchansky** [fyne-io/examples#14]
The hands on the clock look not anti-aliased:
![Clock light](https://raw.githubusercontent.com/fyne-io/examples/develop/img/clock-light.png)

Does the `fyne-io/fyne` support anti-aliasing? Can it be enabled for examples?

**Comment by andydotxyz** [comment]
Thanks for the report. It was blending but incorrectly - that has been resolved upstream.

`go get -u fyne.io/fyne`

Then running the example again should work as expected.
