### ISSUE TITLE
"sorry, unimplemented: 64-bit mode not compiled"

### ISSUE THREAD

**Issue by shilangyu** [fyne-io/examples#15]
Hi, im trying to run the examples however im getting an error.
First i install fyne with `go get -u fyne.io/fyne`, no errors.
Then i proceed to `go get -u github.com/fyne-io/examples` which fails with the following error:
```
# fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
# fyne.io/fyne/vendor/github.com/go-gl/gl/v3.2-core/gl
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
```
gcc:
```
> gcc --version
gcc.exe (i686-posix-dwarf-rev0, Built by MinGW-W64 project) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
Windows 10

**Comment by andydotxyz** [comment]
It sounds like you have Mingw64 in 32 bit mode on a 64bit computer? The i686 gcc can only build 32bit binaries so you probably need to install the x86_64 version.

**Comment by shilangyu** [comment]
Oops! Installing the x86_64 version did work, thank you.

**Comment by maietta** [comment]
> Oops! Installing the x86_64 version did work, thank you.

Didn't work in my case.

**Comment by andydotxyz** [comment]
The message is saying you don't have a 64bit C compiler - which you need for a 64 bit computer. 
There are various different tools, but our recommended install is https://developer.fyne.io/started/ .

**Comment by maietta** [comment]
Thanks, @andydotxyz.

Your suggestion worked for me.

Switched out MingGW-64 environment for the LLVM-Mingw project, updating my environment paths to point to the bin directory and then rebooting. Don't know why, but MingGW-64 no longer working even after re-install. I was very close to re-installing windows from scratch. I even tried downgrading.

Bonus: I am now able to compile from Git-bash terminal under WSL2 in Windows 11.

Wish the errors were a little more obvious to me.
