### ISSUE TITLE
login 

### ISSUE THREAD

**Issue by rajkumarks7** [fyne-io/examples#22]
can you make a login screen which can take username and password from the screen

**Comment by andydotxyz** [comment]
Absolutely, the latest version of our demo (releasing next week) will include it - you can see the code here: https://github.com/fyne-io/fyne/blob/85790ee40c7570efa530fa8bcd0d2a35bd0860b6/cmd/fyne_demo/screens/window.go#L164

**Comment by rajkumarks7** [comment]
thank you i have created a screen with this one can you help with this one i need the username and password and submit the username and password should save it to the variable.


func login() {
	Workahub := app.New()
	w := Workahub.NewWindow("Workahub - Login")
	w.Resize(fyne.NewSize(300, 280))
	w.CenterOnScreen()

	w.ShowAndRun()

}

**Comment by rajkumarks7** [comment]
i wrote this one but it is unable to take the username and password to variable


func login() {
	Workahub := app.New()
	w := Workahub.NewWindow("Workahub - Login")
	w.CenterOnScreen()
	w.Resize(fyne.NewSize(300, 280))
	w.SetFixedSize(true)
	w.Show()

	w.SetContent(widget.NewVBox(
		widget.NewLabel("Login Details"),
		widget.NewLabel("Username"),

		widget.NewEntry(),
		widget.NewLabel("Password"),
		widget.NewPasswordEntry(),
		widget.NewHBox(
			widget.NewButton("Login", func() {

			}),
			widget.NewButton("Quit", func() {
				Workahub.Quit()
			}),
		),
	))

	w.ShowAndRun()

}

**Comment by rajkumarks7** [comment]
i am getting error when i use username:=widget.NewEntry()
and password:=widget.NewPasswordEntry()

**Comment by andydotxyz** [comment]
If you share the error then someone might be able to help.

**Comment by rajkumarks7** [comment]
i am unable to use username:=widget.NewEntry() i am getting error as ',' is expected near ':='

**Comment by rajkumarks7** [comment]
how to get the username and password from the above screen just i need it i will use it in backend an api to authincate it by sending the username and password in form of json

**Comment by andydotxyz** [comment]
Try looking at the link I posted again - it shows how to do that, I don’t think you are setting up variables properly.

**Comment by rajkumarks7** [comment]
i did sir but i am  not getting it. thank you

**Comment by rajkumarks7** [comment]
how are you calling it ? i mean the function which you should me

**Comment by andydotxyz** [comment]
The code is all there to be browsed. That was a button callback so it happened on tapping.

If you have not already I recommend https://tour.golang.org and https://tour.fyne.io

**Comment by andydotxyz** [comment]
Closing as off topic, this appears to relate to Go syntax and there are better resources online than this to help with that.
