### ISSUE TITLE
issue when trying to build into windows

### ISSUE THREAD

**Issue by rajkumarks7** [fyne-io/examples#23]
..\vendor\fyne.io\fyne\internal\painter\gl\gl_core.go:11:2: cannot find package "." in:
	c:\Go\src\github.com\go-gl\gl\v3.2-core\gl
..\vendor\fyne.io\fyne\internal\driver\glfw\clipboard.go:6:2: cannot find package "." in:
	c:\Go\src\github.com\go-gl\glfw\v3.3\glfw

**Comment by andydotxyz** [comment]
Can you please share the command you are using to compile?
And the details of your windows environment...

**Comment by rajkumarks7** [comment]
command:" go run github.com/workahub "
i am using a windows10 64bit

**Comment by rajkumarks7** [comment]
i was getting the above error when i was trying to build windows version of our app using linux system

**Comment by andydotxyz** [comment]
> command:" go run github.com/workahub "

This doesn't look like the full command, as the repository name is missing.

**Comment by andydotxyz** [comment]
> build windows version of our app using linux system

Do you mean running on windows from linux subsystem, or are you cross-compiling for Windows from a Linux computer?

**Comment by rajkumarks7** [comment]
i was using cross compiling but now i am using the windows system to develop
windows version of the app.

**Comment by andydotxyz** [comment]
Which attempt do the errors above relate to? Is there any more information you can provide?

**Comment by rajkumarks7** [comment]
i am getting when the error when ever i run the code in windows os or when i try to build the app in windows. i get the error can i get any solution for the above error. i am getting the above error when ever i run the code.

**Comment by andydotxyz** [comment]
Can you please share the details of directory, command and exact output? The command above does not match the errors you posted so I cannot figure out what is wrong. when you say "the code" which code do you mean? Which set of instructions are you following?

Any more information will help to solve this for you.

**Comment by rajkumarks7** [comment]
hey no problem solved the error thank you for responding .but got another error like when ever i am running the program it is saying the error as "panic: Run() or ShowAndRun() must be called from main goroutine" i am using the windows10 64bit

**Comment by rajkumarks7** [comment]
package main

import (
	"fmt"
	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/layout"
	"fyne.io/fyne/widget"
)

var UserName string
var PassWord string

func main(){
	login()
}

var projectname string
func project() {
	workahubs := app.New()

	w := workahubs.NewWindow("workahub")
	w.CenterOnScreen()
	w.Resize(fyne.NewSize(400, 280))
	w.SetFixedSize(true)
	w.Show()

	navbar := widget.NewToolbar(widget.NewToolbarSpacer(),
		&toolbarLabel{},
		widget.NewToolbarSpacer())
	submit := widget.NewButton("submit", func() {
		fmt.Println(projectname)
		if len(projectname) != 0 {
			w.Close()

		}
	})
	submit.Style = widget.PrimaryButton
	buttons := widget.NewHBox(layout.NewSpacer(),
		submit, layout.NewSpacer(),
	)
	projects := widget.NewVBox(navbar, widget.NewGroup("select project", layout.NewSpacer(), widget.NewVBox(widget.NewButton("training", func() { projectname = "training" }), widget.NewButton("workahub", func() { projectname = "workahub" }), widget.NewButton("IIT/IIM", func() { projectname = "iit/iim" })), layout.NewSpacer()))
	container := fyne.NewContainerWithLayout(layout.NewBorderLayout(projects, buttons, nil, nil), projects, buttons)
	w.SetContent(container)

	w.ShowAndRun()
}

var label *widget.Label

type toolbarLabel struct {
}

func (t *toolbarLabel) ToolbarObject() fyne.CanvasObject {
	label = widget.NewLabel("Projects")
	return label
}

func login(){
		Workahub := app.New()
		w := Workahub.NewWindow("Workahub - Login")

		w.Resize(fyne.NewSize(300, 200))
		w.CenterOnScreen()
		w.SetFixedSize(true)
		w.Show()
		form := widget.NewForm()
		head := widget.NewLabelWithStyle("Workahub", fyne.TextAlignCenter, fyne.TextStyle{Bold: true})
		form.Append("", head)
		Username := widget.NewEntry()
		Username.SetPlaceHolder("Username")
		form.Append("Username", Username)
		Password := widget.NewPasswordEntry()
		Password.SetPlaceHolder("Password")
		form.Append("Password", Password)
		message := widget.NewLabelWithStyle("Invalid Credentials", fyne.TextAlignCenter, fyne.TextStyle{Bold: true})
		message.Hide()
		submit := widget.NewButton("Submit", func() {
			UserName = fmt.Sprint(Username.Text)
			PassWord = fmt.Sprint(Password.Text)
			w.Close()
			project()

		})
		submit.Style = widget.PrimaryButton
		button := widget.NewHBox(layout.NewSpacer(), submit, layout.NewSpacer())

		form.Append("", button)
		w.SetContent(fyne.NewContainerWithLayout(
			layout.NewBorderLayout(form, message, nil, nil), form, message,
		))
		w.ShowAndRun()


}
i am getting second screen blank in windows but it is working in the linux

**Comment by rajkumarks7** [comment]
![blank screen1](https://user-images.githubusercontent.com/64638741/84123525-92345000-aa57-11ea-851f-045618729798.png)

**Comment by andydotxyz** [comment]
Please only create one application per runtime.
The second application running, in a goroutine, is not supported - if you upgrade to v1.3 you will notice that it panics on the second `ShowAndRun()`.

Create 1 application, and from it create your first window, call `ShowAndRun()` then for your second create a new window from the same application and call just `Show()`. The application is already running and you should not call run twice.

**Comment by andydotxyz** [comment]
Closing as not an issue. If you have further problems witth the toolkit please use the [fyne](/fyne-io/fyne/issues/new/choose) repository for opening an issue, this is unrelated to the examples.

**Comment by rajkumarks7** [comment]
Can you please give me a example how to write.

**Comment by rajkumarks7** [comment]
By the way thank you for your help sir

**Comment by andydotxyz** [comment]
Can you be more specific as to what does not make sense? within our examples and tutorials you should find what you want. The `fyne_demo` app loads additional windows (see https://github.com/fyne-io/fyne/blob/master/cmd/fyne_demo/screens/window.go).

We don't really provide bespoke code assistance through GitHub issues - if you would like more support there are various options at https://fyne.io/support/.
