### ISSUE TITLE
I've fyne-cross built examples for Windows but it does not run

### ISSUE THREAD

**Issue by DaleEMoore** [fyne-io/examples#25]
Howdy all y'all,

I'm looking for suggestions to determine what is wrong. I've used fyne-cross to build an executable for Windows and run it on my Windows 10 VM only to find that it does not run. I've found no events tied to it in the event viewer. And I get no error message.

I thought I was doing pretty good here...

Any suggestions you have to determine what's going it is very much appreciated,
Dale

**Comment by DaleEMoore** [comment]
Perhaps this question should be asked in the fyne-cross project...?

**Comment by Jacalz** [comment]
Hi @DaleEMoore 👋 Would you mind sharing what version on Fyne that you were using, what version of fyne-cross and what command you used when cross compiling using fyne-cross?

**Comment by DaleEMoore** [comment]
Hi @Jacalz, I don't mind at all and I'm sorry I didn't think to do this with the original post!

My go.mod:
>module github.com/fyne-io/examples
>
>go 1.12
>
>require (
>	fyne.io/fyne v1.3.0
>	github.com/Knetic/govaluate v3.0.0+incompatible
>	github.com/go-gl/glfw v0.0.0-20200420212212-258d9bec320e // indirect
>	github.com/go-gl/glfw/v3.3/glfw v0.0.0-20200420212212-258d9bec320e // indirect
>	github.com/kr/text v0.2.0 // indirect
>	github.com/stretchr/testify v1.6.1
>	golang.org/x/image v0.0.0-20200609002522-3f4726a040e8 // indirect
>	golang.org/x/mobile v0.0.0-20200329125638-4c31acba0007 // indirect
>	golang.org/x/net v0.0.0-20200602114024-627f9648deb9 // indirect
>	golang.org/x/sys v0.0.0-20200615200032-f1bc736245b1 // indirect
>	golang.org/x/text v0.3.3 // indirect
>	gopkg.in/yaml.v3 v3.0.0-20200615113413-eeeca48fe776 // indirect
>)
>
>replace golang.org/x/mobile => github.com/fyne-io/mobile v0.0.0-20191204153723-f14fb9562406

dalem@QnD3:~/go/src/goLang/src/examples$ fyne-cross --version
fyne-cross version 1.5.0

dalem@QnD3:~/go/src/goLang/src/examples$ fyne-cross -v --targets=android,linux/amd64,windows/386 --output=exMW --appID exMW.mooreworks.net >t1

And the "v1" output from that fyne-cross execution:
[t1.log](https://github.com/fyne-io/examples/files/4795074/t1.log)

I appreciate your time!
Dale

**Comment by andydotxyz** [comment]
If you run the built app from the commandline do you see any errors?
My suspicion is that your VM does not have an OpenGL supporting graphics driver...

**Comment by DaleEMoore** [comment]
Howdy Andy,

I think you are on to something!

>dalem@QnD3:~/go/src/goLang/src/examples$ clear; GOOS=windows go build
>../../../../pkg/mod/fyne.io/fyne@v1.3.0/internal/painter/gl/gl_core.go:11:2: build constraints exclude all Go files in /home/dalem/go/pkg/mod/github.com/go-gl/gl@v0.0.0-20190320180904-bf2b1f2f34d7/v3.2-core/gl
>../../../../pkg/mod/fyne.io/fyne@v1.3.0/internal/driver/glfw/clipboard.go:6:2: build constraints exclude all Go files in /home/dalem/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200420212212-258d9bec320e

Perhaps you could point me at some installation instructions and I can stop pestering y'all,
Dale

**Comment by DaleEMoore** [comment]
My solution was to provision one of the http://modern.ie Windows VMs with git and go then clone my repo and go build my .EXE. Of course TESTing in the VirtualBox failed miserably until I discovered that I needed Settings, Display, Screen, Controller: VBoxSVGA, Enable 3D Acceleration. And now I can Develop and test for Windows.

Thanks!!!
