### ISSUE TITLE
mouse events on canvas - bounding box

### ISSUE THREAD

**Issue by bikedel** [fyne-io/examples#29]
hello

I would like to be able to draw a bounding box around an object in an image. Desktop.

How do I go about getting the mouse events from a canvas that has an image in it?

Is it possible to layer a canvas on top of  another canvas with opacity?

Thanks

**Comment by andydotxyz** [comment]
To draw around an object you will need another object, perhaps a rectangle with `StrokeColor` and `StrokeWidth`. Add both items to a `container.NewMax` and they will draw one over the other at the same size.

Mousse events are sent to widgets that are under them. To get a mouse event directly either extend or implement a widget and add the appropriate handlers. https://developer.fyne.io/tutorial/extending-widgets

A canvas is the drawing area, it cannot be inserted into another canvas.
By canvasObjects can be drawn over each other using a `Container` or `Widget`.

**Comment by andydotxyz** [comment]
I hope those comments are helpful.
This is not really an issue for the `examples` repo so I am closing.
For other support channels why not consider our Slack group etc linked from https://fyne.io

**Comment by bikedel** [comment]
Hi Andy

Thanks for your quick response and for pointing me in the right direction.
