### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ghkerh** [fyne-io/examples#31]
I obtain this result:
# github.com/fyne-io/examples/bugs
../../../../go/pkg/mod/github.com/fyne-io/examples@v0.0.0-20210907081108-453b4ac4409d/bugs/button.go:34:10: assignment mismatch: 1 variable but fyne.CurrentApp().Driver().RenderedTextSize returns 2 values

What could I do?

**Comment by andydotxyz** [comment]
Apologies, one of the demos used an internal API that was changed in v2.1.0 - I have updated the repo, just pull the code and it should work again

**Comment by ghkerh** [comment]
Thanks but I don't know which line of code to delete... (not to mention the
icon problems!)
I'm new to Github, Go and Fyne, and without explanations I find it very
confusing.
Sorry.

Le mer. 29 sept. 2021 à 14:10, Andy Williams ***@***.***> a
écrit :

**Comment by andydotxyz** [comment]
No code editing needed - just `git pull` and it will be fixed.
