### ISSUE TITLE
Fyne_demo Source Code

### ISSUE THREAD

**Issue by elibroftw** [fyne-io/examples#34]
Where can I find the source code for fyne_demo? I can find it in explorer but where is it online?

**Comment by Jacalz** [comment]
What do you mean with that you can see it in the explorer? If you have downloaded it by cloning the Fyne repository, it will be in that very same repository online. You can find it here (not in the examples repo): https://github.com/fyne-io/fyne/tree/master/cmd/fyne_demo.
