### ISSUE TITLE
Add two example widgets. A clock widget and an animated widget 

### ISSUE THREAD

**Issue by stuartdd2** [fyne-io/examples#35]
As discussed on Slack fyne Gophers I have two examples of widgets that I would like to add to the fyne-io/examples project. 

It was suggested that the clock widget should be added to fyne-x but both widgets were written as examples for other devs to base their widgets off so I think fyne-io/examples is a better fit.  

The code is currently here! https://github.com/stuartdd2/fyne-widget-example

I have read the guide to creating pull requests (via a black-hole when I clicked rebase!).

I need to create a branch. I assume that is a branch off fyne-io/examples development, which I cannot do.

I have used git for years but only in the context of a large corporation that hosted it's own managed instance so I am a little out of my depth. This is the first time I plan to contributed to public github repositories so I need a little assistance to get started. I hope to continue contributing to this and other projects in the future.

I think I need to have access to create the branch.

Can you help?

**Comment by stuartdd2** [comment]
Ok. Found a better guide that uses fork rather than creating a branch. I understand this and can work with this it is far more familiar to me a s a process.

**Comment by andydotxyz** [comment]
You should create a branch per-PR - but do so on your own fork.
I don't think this is still an issue, closing
