### ISSUE TITLE
Raport from building examples

### ISSUE THREAD

**Issue by szopeno** [fyne-io/examples#5]
OpenSuse Leap 42.3, after installing EFL + evas1

in go/src/github.com/fyne-io/examples>
go build . 

RESULT:
# github.com/fyne-io/examples/bugs
bugs/board.go:184: undefined: strings.Builder
bugs/button.go:52: cannot use b.button (type *bugButton) as type fyne.CanvasObject in argument to canvas.Refresh:
        *bugButton does not implement fyne.CanvasObject (missing Position method)
bugs/button.go:127: cannot use bugRenderer literal (type *bugRenderer) as type fyne.WidgetRenderer in return argument:
        *bugRenderer does not implement fyne.WidgetRenderer (missing BackgroundColor method)
bugs/main.go:73: cannot use g.renderer (type *gameRenderer) as type fyne.WidgetRenderer in return argument:
        *gameRenderer does not implement fyne.WidgetRenderer (missing BackgroundColor method)
bugs/main.go:108: impossible type assertion:
        *bugButton does not implement fyne.CanvasObject (missing Position method)
bugs/main.go:177: cannot use newButton("", code, func literal) (type *bugButton) as type fyne.CanvasObject in append:
        *bugButton does not implement fyne.CanvasObject (missing Position method)
bugs/main.go:232: cannot use game (type *game) as type fyne.CanvasObject in argument to game.window.SetContent:
        *game does not implement fyne.CanvasObject (missing Position method)
# github.com/fyne-io/examples/life
life/main.go:195: cannot use g.renderer (type *gameRenderer) as type fyne.WidgetRenderer in return argument:
        *gameRenderer does not implement fyne.WidgetRenderer (missing BackgroundColor method)
life/main.go:323: cannot use game (type *game) as type fyne.CanvasObject in argument to window.SetContent:
        *game does not implement fyne.CanvasObject (missing Position method)
# github.com/fyne-io/examples/solitaire
solitaire/game.go:103: cannot use NewTable(game) (type *Table) as type fyne.CanvasObject in argument to w.SetContent:
        *Table does not implement fyne.CanvasObject (missing Position method)
solitaire/render.go:111: cannot use t.table (type *Table) as type fyne.CanvasObject in argument to canvas.Refresh:
        *Table does not implement fyne.CanvasObject (missing Position method)
solitaire/table.go:72: cannot use t.renderer (type *tableRender) as type fyne.WidgetRenderer in return argument:
        *tableRender does not implement fyne.WidgetRenderer (missing BackgroundColor method)
solitaire/table.go:76: card.baseObject.Position.X undefined (type func() fyne.Position has no field or method X)
solitaire/table.go:76: card.baseObject.Position.Y undefined (type func() fyne.Position has no field or method Y)
solitaire/table.go:80: card.baseObject.Position.X undefined (type func() fyne.Position has no field or method X)
solitaire/table.go:80: card.baseObject.Size.Width undefined (type func() fyne.Size has no field or method Width)
solitaire/table.go:80: card.baseObject.Position.Y undefined (type func() fyne.Position has no field or method Y)
solitaire/table.go:80: card.baseObject.Size.Height undefined (type func() fyne.Size has no field or method Height)
# github.com/fyne-io/fyne/driver/efl
../fyne/driver/efl/canvas.go:38: cannot use &x (type *C.int) as type *C.Evas_Coord in argument to func literal
../fyne/driver/efl/canvas.go:38: cannot use &y (type *C.int) as type *C.Evas_Coord in argument to func literal
../fyne/driver/efl/canvas.go:275: cannot use &oldWidth (type *C.int) as type *C.Evas_Coord in argument to func literal
../fyne/driver/efl/canvas.go:275: cannot use &oldHeight (type *C.int) as type *C.Evas_Coord in argument to func literal
../fyne/driver/efl/canvas.go:501: undefined: math.Round

I am puzzled especially by undefined math. Round and undefined strings.Builder. It's possible that I am mising something obvious; but after spending some half an hour on this (mostly on installing EFL), I am not motivated enough to try any more ideas

**Comment by andydotxyz** [comment]
I’m sorry you’re having a bad experience getting set up! This seems to a combination of lots of different causes.

* Go is maybe <= 1.10
* Examples looks like it is older than Fyne (recent API changes)
* EFL is too old? (Needs 1.18)

There may be other issues too but I’m not sure.

Good news: we are changing the default driver to not use efl later this week.
Recommendation: update Go, then on Monday update Fyne and Examples repos. With any luck it should all work then :)

**Comment by szopeno** [comment]
Thanks for the answer. I will definetely try Fyne next week and I am updating go right now.

**Comment by andydotxyz** [comment]
Apologies for the delay but the drivers have now changed over.
If you update the fyne and examples repository it should all work :)

**Comment by ddkwork** [comment]
i have same problem

**Comment by andydotxyz** [comment]
Do you have a recent enough version of Go @DiskGetor? Fyne requires 1.12 or above
